Correct line 62: TypeError
Was receiving this error (python 3.5.2):
  File "strandtest.py", line 62, in rainbowCycle
    strip.setPixelColor(i, wheel(((i * 256 / strip.numPixels()) + j) & 255))
TypeError: unsupported operand type(s) for &: 'float' and 'int'

Just needed to cast the result of ((i * 256 / strip.numPixels()) + j) to an int.